[project]
name = 'decentralized-pharmaceutical-supply-optimization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.drug-distribution-optimizer]
path = 'contracts/drug-distribution-optimizer.clar'
clarity_version = 3
epoch = 3.1

[contracts.shortage-mitigation-coordinator]
path = 'contracts/shortage-mitigation-coordinator.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
